pipeline {
    agent {
        docker { image 'maven:3.6.1-jdk-8-slim' }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn --version'
            }
        }
    }
}

